### ISSUE TITLE
Guacamole - Virtual Desktop Service - Need to lock down permissions by policy

### ISSUE THREAD

**Issue by stevennewhouse** [Barts-Life-Science/Support#36]
In creating the Virtual Desktop Service, I have the choice of configuring Disabling copy/paste/upload/download/expose externally.

Not sure if this is due to my permissions... or a general feature. Need to check and lock down.

**Comment by TonyWildish-BH** [comment]
it's a feature that all Workspace Admins will have access to. Before we can lock it down fully, we need a solution for pushing things into the VMs, like Gitea or MySQL credentials. Otherwise the user is going to be typing in long, meaningless strings in order to get access to things.

We need to resolve this before the Beta.

**Comment by akolensky** [comment]
Refrence ticket to [Add functionality to push a file ...](https://github.com/Barts-Life-Science/AzureTRE/issues/54)

**Comment by TonyWildish-BH** [comment]
Note from pen-testing: The cut/paste buffer seems to allow 262KB, which is rather a lot. If we continue to permit cut/paste, we may want to reduce that to something much smaller, like 2K. That would be enough for platform operations (SAS URLs) etc.
